import 'server-only'
import Anthropic from '@anthropic-ai/sdk'
import { zodOutputFormat } from '@anthropic-ai/sdk/helpers/zod'
import { z } from 'zod'
import { CitationFields, SourceType } from './types'
import { sanitizeFieldsForValidation } from './utils'

const MODEL = 'claude-sonnet-4-6'

const ValidationSchema = z.object({
  isCorrect: z.boolean(),
  correctedFootnote: z.string().nullable(),
  correctedSubsequent: z.string().nullable(),
  correctedBibliography: z.string().nullable(),
  issues: z.array(z.string()),
  rule: z.string(),
  confidence: z.enum(['high', 'medium', 'low']),
})

export interface CitationTexts {
  footnote: string
  subsequent: string
  bibliography: string
}

export interface ValidationResult {
  isCorrect: boolean
  correctedFootnote?: string
  correctedSubsequent?: string
  correctedBibliography?: string
  issues?: string[]
  rule?: string
  confidence: 'high' | 'medium' | 'low'
}

// AGLC4 rule text embedded directly — do not attempt to load the source PDF at runtime.
const RULES_BY_SOURCE_TYPE: Record<SourceType, string> = {
  case: `AGLC4 Chapter 2 — Cases.
Reported decisions (r 2.2): [Case Name] (Year) Volume ReportAbbreviation StartingPage, Pinpoint (Judge). Year is in round brackets for volume-organised report series (eg CLR, FCR, VR, NSWLR, ALR, HCA, FCA) and in square brackets for year-organised series (eg Qd R, NZLR). If a volume number is used it sits between the year and the report abbreviation. Case names are italicised; ordinal numbers appear in square brackets, eg [No 2]. Pinpoints follow the starting page after a comma; paragraph pinpoints are in square brackets, page pinpoints are bare numbers. No full stops in abbreviations (CLR not C.L.R.).
Unreported with medium neutral citation (r 2.3.1): [Case Name] [Year] CourtCode CaseNumber, [Paragraph] (Judge). Year always square-bracketed; pinpoint is always a paragraph number in square brackets.
Unreported without medium neutral citation (r 2.3.2): [Case Name] (Court, Judge(s), Full Date) Pinpoint. Pinpoint is a bare page number.
General (ch 1): every footnote ends with a full stop.`,
  legislation: `AGLC4 Chapter 3 — Legislation.
Statutes (r 3.1): [Act Title Year] (Jurisdiction) PinpointType PinpointValue. The Act title and year are italicised together as one unit, eg *Privacy Act 1988*. The jurisdiction abbreviation (Cth, Vic, NSW, Qld, WA, SA, Tas, ACT, NT) follows in round brackets with no full stops — Cth, never C'th. The Australian Constitution is cited without jurisdiction brackets, eg *Australian Constitution* s 51(xxvi). Pinpoint abbreviations (s, ss, sch, pt, div, reg) carry no full stops.`,
  journal: `AGLC4 Chapter 5 — Journal Articles.
Format (r 5.1-5.7): Author(s), 'Article Title' (Year) Volume(Issue) [Journal Name] StartingPage, Pinpoint. Multiple authors are joined with commas and 'and' before the last, no Oxford comma. The article title is in single quotation marks, never italicised. Year is in round brackets for volume-organised journals; square brackets for year-organised journals with no volume, in which case the issue number alone appears in round brackets after the year, eg [2000] (1). The journal name is italicised. Pinpoints follow the starting page after a comma.`,
  book: `AGLC4 Chapter 6 — Books.
Whole book (r 6.1-6.4): Author(s), [Title] (Publisher, Year) Pinpoint. If not a first edition: (Publisher, Edition, Year), eg (Oxford University Press, 2nd ed, 2005). The title is italicised. The pinpoint is a bare page number with no comma before it.
Book chapters in edited books (r 6.6.1): ChapterAuthor(s), 'Chapter Title' in Editor(s) (ed) or (eds), [Book Title] (Publisher, Year) StartingPage, Pinpoint. 'ed' for one editor, 'eds' for more than one. The book title is italicised; the chapter title is in single quotation marks.
The source fields include a bookType field ('book' or 'chapter') that authoritatively selects which of the two formats above applies — validate the given footnote/subsequent/bibliography strictly against whichever format bookType names. chapterAuthors, chapterTitle, editors, and startingPage may all be populated even when bookType is 'book' (Pinpoint extracts both a whole-book and a chapter reading of the source up front so a student can freely switch between them) — when bookType is 'book', ignore those chapter-only fields entirely and validate only against the whole-book format; never treat their presence as a reason to "correct" a whole-book citation into chapter form.`,
  report: `AGLC4 Chapter 7, r 7.1 — Reports and Similar Documents.
Format (r 7.1.1): Author(s), [Title] (DocumentType or SeriesNumber, Date) Pinpoint. The author is omitted entirely (including the leading comma) when not prominently indicated, eg for a Prime Minister's report with no named author. If a series number is given (eg 'Report No 129') it replaces the plain document type inside the parenthetical, followed by a comma and the date. The title is italicised.`,
  researchPaper: `AGLC4 Chapter 7 — Conference Papers, Theses, and Working/Research Papers.
Format: Author(s), 'Title' (DocumentType, Institution, Date) Pinpoint. Unlike a report, the title is in single quotation marks — never italicised — because these are papers within or presented to a larger body (a conference, a university, a working paper series), not standalone publications. DocumentType is a short descriptor: 'Conference Paper' for a paper presented at a conference (the Institution field then holds the conference name and Date is the full date, eg '4 July 2015'); 'PhD Thesis', 'Masters Thesis', or 'Honours Thesis' for a thesis (Institution holds the university name and Date is usually just the year); 'Working Paper' or 'Research Paper' for an unpublished/preprint paper (Institution holds the publishing body, and a series number, if any, eg 'Working Paper No 5', is appended to the document type inside the brackets). The pinpoint is a bare page/paragraph number with no comma before it, matching a report or a whole book.`,
  website: `AGLC4 Chapter 7, r 7.15 — Internet Materials.
Format: Author(s), 'Document Title', [Website Name] (Document Type, Date) Pinpoint <URL>. The author is omitted entirely when not indicated, or when it is identical to the website name. The document title is in single quotation marks, not italicised; the website name is italicised. Document type (Web Page, Blog Post, Forum Post) and date sit in round brackets — if no date is available, just the document type with no comma. The URL sits in angle brackets at the end, before the full stop. This rule is used only when no other AGLC4 rule applies to the source.`,
  newspaper: `AGLC4 Chapter 7, r 7.11.2 — Electronic Newspaper Articles.
Format: Author(s), 'Article Title', [Newspaper Name] (online, Date) Pinpoint <URL>. The author is omitted entirely (including the leading comma) when the article is unbylined, eg an unattributed wire-service report. The article title is in single quotation marks, not italicised; the newspaper's own masthead name is italicised. The parenthetical is always the literal word 'online' followed by a comma and the full date (day, month, year) — there is no separate page number the way a print newspaper article would have one. The URL sits in angle brackets at the end, before the full stop. This rule applies specifically to newspaper articles (a masthead with journalistic bylines, eg ABC News, The Sydney Morning Herald), taking precedence over the generic r 7.15 website rule where it applies.`,
  otherLegislativeMaterial: `AGLC4 Chapter 3 — covers five distinct categories; identify which one this citation is for from its shape and validate against that specific sub-rule only.
Bill (r 3.2): [Bill Title Year] (Jurisdiction) Pinpoint. Cited exactly like an Act, except the title and year are NEVER italicised — this is the key departure from r 3.1. 'cl'/'sub-cl' are the typical pinpoint designations.
Explanatory Material (r 3.7): Label, [Bill Citation per r 3.2 above] Pinpoint. Label is 'Explanatory Memorandum', 'Explanatory Statement', 'Explanatory Note', or 'Explanatory Notes' depending on what the jurisdiction itself calls it — never italicised, matching the Bill citation it wraps.
Gazette (r 3.9.1): [Author, ]['Notice Title' in ]Jurisdiction, [Italic]Gazette Name, No X, Date[, StartingPage[, Pinpoint]]. Author and notice title are both present or both absent together (a citation to a specific notice within the gazette needs both to make sense); a whole-gazette citation has neither, and no page numbers either. The gazette's own name is italicised; a cited notice's title is in single quotation marks.
Court Practice Direction/Note: Court, [Italic]PracticeType No X of Year: Title[/Italic], Date. PracticeType is 'Practice Note' or 'Practice Direction' depending on what the issuing court calls it. The direction/note's own name — the 'PracticeType No X of Year: Title' segment — is italicised as a unit, the same way an Act's or a gazette's own name is; the court and date framing it are not part of the italicised span. Date is the direction/note's own issuing/signing date (often found at the very end of the document, near a signature block), not a commencement date if the two differ.
Constitution (r 3.6): identical to an ordinary Act citation (r 3.1) — [Title Year] (Jurisdiction) Pinpoint, title and year italicised together. The one deliberate exception: the bare Commonwealth 'Australian Constitution' takes NO year and NO jurisdiction bracket at all — never 'Australian Constitution (Cth)' — while every state/territory's own constituting Act (eg 'Constitution Act 1902 (NSW)', 'Constitution of Queensland 2001 (Qld)') is cited with its year and jurisdiction exactly like any other Act. Self-government Acts (eg 'Australian Capital Territory (Self-Government) Act 1988 (Cth)') are Cth Acts, cited normally with the (Cth) bracket.`,
  internationalMaterial: `AGLC4 Chapter 8/9/14 — International Material, covering four distinct categories under one source type (mirroring how 'otherLegislativeMaterial' bundles five AGLC4 ch 3 categories) — identify which this citation is for from the source fields' own 'subtype' value and validate against that specific sub-rule only; never judge one subtype's citation against another subtype's format.
Treaty (subtype 'treaty', AGLC4 r 8.1-8.7): open multilateral — [Treaty Title], opened for signature [Date], [Treaty Series] (entered into force [Date]) Pinpoint; if not yet in force, the '(entered into force ...)' clause is omitted entirely. Bilateral/trilateral where the parties aren't already in the title — [Treaty Title], [Party]-[Party], signed [Date], [Treaty Series] (entered into force [Date]) Pinpoint, parties joined with an en dash (not a hyphen), using conventional shortened state names (eg 'Australia' not 'Commonwealth of Australia'). The treaty title is always italicised. A treaty series number is frequently unavailable from the source itself (eg the treaty's own signed text, or a depositary/agency circular reproducing it, predates the UN registration that assigns it one) — an empty treaty series is not itself an error to correct; the '(entered into force ...)' clause (or, if that's also empty, whatever the last populated piece of content is) simply has no series number in front of it and no comma is expected there either. r 8.3.2's merged form: for a bilateral/trilateral treaty whose signature date and entry-into-force date are the SAME, the separate 'signed [Date],' clause is correctly dropped entirely and the parenthetical becomes '(signed and entered into force [Date])' instead of '(entered into force [Date])' — eg '..., 1369 UNTS 43 (signed and entered into force 29 June 1982).', never '..., signed 29 June 1982, 1369 UNTS 43 (entered into force 29 June 1982).' with the same date twice. This merged form never applies to an open multilateral treaty (opened for signature, not signed by all parties) — AGLC4 defines no equivalent for that form, so a multilateral treaty citation with matching dates correctly still shows both.
UN Materials (subtype 'unDocument', AGLC4 r 9.2.4): a UN General Assembly declaration or resolution — distinct from a treaty: never opened for signature, ratified, or "entered into force", and carries no treaty series number. Format: [Title], GA Res [ResolutionNumber] ([Session]), UN GAOR, UN Doc [Symbol] ([Date][, adopted AdoptedDate]) Pinpoint. The title is italicised. The literal 'UN GAOR' component appears if and only if the source fields' own 'includeOfficialRecords' flag is set — this is a genuinely separate, independently-set element from Session (r 9.2's own element table lists 'Official Records' and 'Session (and Part) Number' as two different rows), NOT something to infer from whether Session happens to be populated (an earlier version of this validator wrongly did exactly that, since the only two examples on hand at the time — the UDHR, old-style '217A (III)' numbering with 'UN GAOR', and UNDRIP, newer '61/295' numbering without it — happened to also differ on Session, but the two elements are not the same thing). Trust the 'includeOfficialRecords' field as ground truth; only check that the citation TEXT correctly reflects it, never second-guess the flag itself from the resolution-number style. AdoptedDate appears only when the source states an adoption/vote date distinct from the resolution document's own formal date, rendered as ', adopted AdoptedDate' directly inside the same closing parenthesis as Date, not as a separate clause — leave it out entirely when only one date is stated. ResolutionNumber, Session, UnDocSymbol, and AdoptedDate are frequently not all available from a general-audience source — whichever of GA Res.../UN GAOR/UN Doc.../Date are populated appear in that order, comma-separated, with no comma directly before the final '(Date...)' parenthetical; an empty field is not itself an error to correct, just an absent piece. Exception — the Charter of the United Nations itself is cited by its bare title alone, with every other field empty, even though authoritative sources about the Charter typically also state a signature/entry-into-force date the way a treaty's page would — those dates are never included in the Charter's own citation; if the given fields show only a title for a UN Materials source, that is very likely correct rather than an extraction failure to flag.
Foreign Domestic Sources (subtype 'foreignDomestic', AGLC4 Part V) — a foreign case or piece of legislation cited in the style of its own jurisdiction of origin. Identify the specific foreignCountry/foreignCategory combination from the source fields and validate against that specific format only; never judge one country's/category's citation against another's.
Unreported cases (foreignCaseReportType 'unreported-mnc'/'unreported-no-mnc', every country except the US): every Foreign Domestic Sources jurisdiction incorporates AGLC4's own domestic unreported-case rules (r 2.3.1/2.3.2) — NZ (r 21.1.3), UK (r 24.1.5), Malaysia (r 20.1.2, no-MNC only — Malaysian courts don't issue medium neutral citations at all, so an MNC-form Malaysian citation is itself an error to flag) and Singapore (r 22.1.3) each confirm this by name with their own court-identifier table; Canada, Hong Kong and South Africa have no dedicated sub-rule of their own, so the general r 2.3.1/2.3.2 form applies directly. Unreported-MNC: '[Case Name] [Year] CourtCode CaseNumber, [Paragraph] (Judge).' — year always square-bracketed, pinpoint always a paragraph number in square brackets, same as the domestic form. Unreported-no-MNC: '[Case Name] (Court, Judge(s), Full Date) Pinpoint.' — the pinpoint is a BARE page number with NO comma before it, unlike almost every other pinpoint in this app; do not flag the missing comma as an error there.
US Unreported Cases (r 25.1.7) — genuinely different from every other country's unreported form, since US courts have no medium-neutral-citation concept at all: 'Parties' Names (Jurisdiction and Court/District, Docket or Reference No, Full Date) slip op Pinpoint (Judge).' The literal 'slip op' marker precedes the pinpoint and is correctly OMITTED ENTIRELY when there's no pinpoint at all (confirmed by AGLC4's own worked example, 'Red Hat Inc v The SCO Group Inc (D Del, Civ No 03-772-SLR, 6 April 2004).', no trailing 'slip op') — don't flag its absence as missing when the citation has no pinpoint.
Canada Case (r 15.1): cited as an ordinary AGLC4 ch 2 case (Case Name (Year) Volume ReportAbbr StartingPage, Pinpoint (Judge)(Court)) — bracket type (round vs square) follows the report series, eg SCR/FC/Ex CR are square, DLR is round.
Canada Legislation (r 15.2): [Italic Title], StatuteVolumeType+JurisdictionAbbrev Year[ (SessionOrSupp)], c Chapter, Pinpoint — eg '*Privacy Act*, RSC 1985, c P-21'. The title IS italicised (r 15.2.1 says it follows the same rule 3.1.1 convention every ordinary Act title gets) and has 'The' stripped from the start — only the comma directly after the title is called out as deliberately non-italic, not the title itself.
New Zealand Case (r 21.1) / Legislation (r 21.2.1) / Delegated Legislation (r 21.2.2): case is an ordinary ch 2 case; legislation is '[Title Year] (NZ) Pinpoint' (italicised, matching r 3.1 in full); delegated legislation adds 'SR Year/Number' after '(NZ)'.
UK Case (r 24.1): ordinary ch 2 case; 'plc' and the judicial-review 'R (Party)' construction are name conventions the case name should already reflect, not something the validator should flag as wrong when present.
UK Legislation (r 24.2): '[Title Year] (Jurisdiction) Pinpoint' — jurisdiction is one of UK/NI/Scot/Wales/Imp shown in a bracket, or (for pre-1963 UK Parliament Acts only) omitted entirely with the title instead taking a non-italic comma. Per r 24.2.3, a regnal year and chapter number (eg '9 & 10 Eliz 2, c 34') are included ONLY for a statute enacted before 1 January 1963 — a post-1963 UK/NI/Scot/Wales statute has NO number in its citation at all (confirmed directly against every one of r 24.2.2's own worked examples: 'Human Rights Act 1998 (UK) s 6(1).', 'Appropriation Act 2004 (UK).', 'Libraries Act (Northern Ireland) 2008 (NI).', 'Dog Fouling (Scotland) Act 2003 (Scot).', 'Learner Travel (Wales) Measure 2008 (Wales).' — none carries a chapter/'asp'/'anaw'-style number). Confirmed as a real, live mistake this app has actually made: do NOT expect or add a chapter number for a modern (post-1963) UK/NI/Scot/Wales Act just because that IS how those Parliaments/Assemblies cite their own legislation in the real world (eg 'asp 12', '2020 anaw 1') — AGLC4 itself simply omits it; a direct search of the entire AGLC4 guide confirms 'asp'/'nawm'/'anaw'/'asc' don't appear anywhere in it. Only flag a missing regnal-year/chapter pair as an error when 'ukRegnalYear' is actually present in the source fields (ie a genuinely pre-1963 citation) yet the chapter is missing from the citation text. Per r 24.2.4, the pinpoint's own comma is likewise conditional on that chapter: a post-1963 citation takes a bare-space pinpoint like ordinary domestic legislation (eg '... (UK) s 6(1).', no comma), while a pre-1963 one takes the comma-prefixed form (eg '..., 9 & 10 Eliz 2, c 34, s 3.').
UK Delegated Legislation (r 24.3): '[Title Year] (Jurisdiction) InstrumentType Year/Number, Pinpoint' — InstrumentType is SI (UK from 1947)/SR & O (UK 1890-1947)/SR (Northern Ireland).
US Case (r 25.1): 'Case Name, Volume ReportAbbr[SeriesNumber] StartingPage, Pinpoint (Judge) (JurisdictionCourt, Year)' — jurisdiction/court is omitted entirely for US Supreme Court decisions (no 'Sup Ct' or similar), never flag its absence there as an error.
US Legislation Code (r 25.2): '[StatuteTitle, ]TitleOrChapterNo CodeAbbrev § Pinpoint ([Publisher ]Year)' — the statute title, when present, is italicised; many code citations correctly have no year at all (eg '35 USC § 102.') — don't treat a missing year as an error.
US Legislation Session Law (r 25.3): 'StatuteTitle, PublicLawNumber, [OriginalPinpoint, ]VolumeOrYear AbbreviatedName StartingPage[, PagePinpoint][ (Year)]' — federal session laws cite a Stat volume with a trailing '(Year)'; state session laws often use the year itself as the volume marker instead, in which case there is correctly no separate trailing year. The original (pre-volume) pinpoint, when present, is ALWAYS followed by a comma (r 25.3.3) — eg '..., Pub L No 109-243, § 4, 120 Stat 572, 573 (2006).' — do not flag that comma as extraneous. The page-level pinpoint after the starting page is a genuinely separate element from the original pinpoint (r 25.3.6) and both may legitimately appear in the same citation at once, as in that same example ('§ 4' then '573').
US Constitution (r 25.4): the bare constitution title alone, always italicised, eg '*United States Constitution*.' / '*Texas Constitution*.'
Hong Kong Case (r 19.1) / Legislation (r 19.2.1): ordinary ch 2 case; legislation is '[Title] (Hong Kong)[ cap ChapterNumber], Pinpoint' — no year when a chapter number is present (a year appears only for historical/un-numbered ordinances, embedded directly in the title text itself, eg 'Telephone Ordinance 1925').
Malaysia Case (r 20.1) / Legislation (r 20.2.1): ordinary ch 2 case, except the Malayan Law Journal ('MLJ') is volume-organised (round brackets) before 1966 and year-organised (square brackets) from 1966 onward — this is a genuine date-dependent exception, not an inconsistency to flag; legislation is '[Title Year] (Malaysia) Pinpoint'.
Singapore Case (r 22.1) / Legislation (r 22.2.1): ordinary ch 2 case; legislation is EITHER '[Title] (Singapore, cap ChapterNumber, RevisionYear rev ed) Pinpoint' (chapter-numbered Acts) OR '[Title Year] (Singapore) Pinpoint' (non-chapter-numbered) — both are correct, which one applies depends on whether the Act has been assigned a chapter number.
South Africa Case (r 23.1) / Legislation (r 23.2.1): ordinary ch 2 case; legislation is '[Title Year] (Jurisdiction) Pinpoint' where Jurisdiction is 'South Africa' or a provincial abbreviation (eg 'KZN').
European Union / Council of Europe Materials (subtype 'europeanUnion', AGLC4 ch 14.2/14.3) — six categories under 'euCategory'. Identify the specific category from the source fields and validate against that specific format only; never judge one category's citation against another's.
Official Journal of the EU (r 14.2.1): [Italic Document Title] [Year] OJ Series IssueNumber/StartingPage, Pinpoint — eg '[2003] OJ L 1/72, 79.' The series letter is included only for documents published from 1 January 1968 (a bare title with no OJ reference at all, or a pre-1968 'OJ IssueNumber/StartingPage' with no series letter, are both correct depending on the source). The 'S' series (invitations to tender) never has a starting page — just 'OJ S IssueNumber'. The post-2016 digital-only part of the C series uses an 'E/' page prefix instead of a plain '/', eg '[2009] OJ C 3 E/1.' A pre-1974 document may carry a parallel Special Edition citation preceded by a semicolon, eg '[1970] OJ L 224/1; [1970] OJ Spec Ed 623.'
Constitutive Treaty of the EU (r 14.2.2) / Basic Document of the Council of Europe (r 14.3.1): cited as an ordinary ch 8 treaty — [Italic Title], opened for signature Date, TreatySeries (entered into force Date). A short title, when given, is included inline in this FIRST citation too (not just subsequent references) as '(‘*ShortTitle*’)' — confirmed against font-level formatting in the actual AGLC4 PDF that the short title itself is italicised even inside its quote marks, eg '(entered into force 1 November 1998) (‘*ECHR*’).' An 'as amended by [Citation]' clause may follow, comma-joined, when the source is cited with amendment history.
Courts of the European Union (r 14.2.3, the CJEU/General Court/EU Civil Service Tribunal): Reported (in the ECR/ECR-SC) — '*Parties* (CaseNumber) [Year] [Volume ]ReportAbbrev StartingPage, Pinpoint.' — eg 'Costa v ENEL (C-6/64) [1964] ECR 585, 594.' A volume number before the report abbreviation is genuinely optional/rare (most ECR citations have none) — its absence is not an error. Unreported — '*Parties* (CourtName, CaseNumber, ECLI, FullDate) [Pinpoint].' — eg 'Huawei Technologies Co Ltd v ZTE Corporation (Court of Justice of the European Union, C-170/13, ECLI:EU:C:2015:477, 16 July 2015) [9].' The paragraph pinpoint here is BARE-SPACE with no comma before the bracket — '2015) [9]', not '2015), [9]' — this is a genuine departure from the ordinary comma-prefixed pinpoint convention, confirmed directly against AGLC4's own worked example, not an error to flag.
European Court of Human Rights (r 14.3.2) — four formats. Reported, until end of 1995 ('Eur Court HR (ser A)'): '*Parties* (Year) Volume[-Letter] Eur Court HR (ser A) [Pinpoint] [(Judge)].' — eg 'Nasri v France (1995) 320-B Eur Court HR (ser A) 28 (Judge Pettiti).' This series has NO starting page element at all (pagination restarts for each case) — the bare-space number after '(ser A)' is the PINPOINT, not a starting page, and is correctly absent from many citations, eg 'Loizidou v Turkey (Preliminary Objections) (1995) 310 Eur Court HR (ser A).' Reported, from 1996 ('Eur Court HR', year-organised): '*Parties* [Year] VolumeRoman Eur Court HR StartingPage, Pinpoint.' — eg 'Bouchelkia v France [1997] I Eur Court HR 47, 67.' (ordinary comma-prefixed pinpoint here, unlike ser A). Unreported: '*Parties* (European Court of Human Rights, Chamber, Application No(s) Number, Full Date) [Pinpoint].' — bare-space paragraph pinpoint, same convention as CJEU unreported above. Pleadings (Eur Court HR (ser B), until 1988): ''Document Title', *Parties* [Year] Eur Court HR (ser B) StartingPage, Pinpoint.' — the document title is quoted, not italicised. Any of these four may carry an italicised '(*Phase*)' parenthetical directly after the parties' names where the source states one (eg '(Preliminary Objections)', '(Just Satisfaction)') — its absence is the normal case, not an omission to flag.
European Commission of Human Rights (r 14.3.3): '*Parties* (Year) Volume Eur Comm HR StartingPage, Pinpoint.' — eg 'Klass v Federal Republic of Germany (1978) 1 Eur Comm HR 20, 29.' A volume number and starting page are always required here (unlike the CJEU/ECtHR formats above, where they're sometimes absent) — their absence IS worth flagging for this one category specifically.`,
  otherSources: `AGLC4 Chapter 7 — covers seven distinct categories under one source type (mirroring how 'otherLegislativeMaterial' bundles five ch 3 categories and 'internationalMaterial' bundles three) — identify which this citation is for from the source fields' own 'subtype' value and validate against that specific sub-rule only; never judge one subtype's citation against another subtype's format.
Dictionary (subtype 'dictionary', r 7.6): hard copy — [Italic Dictionary Title] (Edition ed, Year) 'Entry' (def N); online — [Italic Dictionary Title] (online at RetrievalDate) 'Entry' (def N). The dictionary title IS italicised; the entry word is quoted and explicitly NOT italicised (the rule text says so directly). The '(def N)' / entry-abbreviation parenthetical is entirely optional and dropped when there's only one entry/definition for the word — its absence is not an error.
Legal Encyclopedia (subtype 'legalEncyclopedia', r 7.7): hard copy — Publisher, [Italic Title of Encyclopedia], vol N (at Date) TitleNumber Name of Title, 'ChapterNumber Name of Chapter' [Paragraph]; online — Publisher, [Italic Title] (online at RetrievalDate) TitleNumber Name of Title, 'ChapterNumber Name of Chapter' [Paragraph]. Note the punctuation genuinely differs between forms: hard copy has a comma before 'vol N', online has no comma before '(online at ...)'. Some encyclopedias (eg Halsbury's Laws of England) don't number their titles at all — a missing title number before 'Name of Title' is correct, not an omission to flag.
Speech (subtype 'speech', r 7.3): Author, 'Title' (Speech, Institution/Forum, Full Date) Pinpoint. For a named lecture, the lecture's own name (with any leading 'The' and ordinal number already stripped, eg 'Lucinda Lecture' not 'The 2013 Lucinda Lecture') replaces the literal word 'Speech' in that position — this is correct per r 7.3, not a missing/wrong document type.
Press and Media Release (subtype 'pressRelease', r 7.4): Author, 'Title' (ReleaseType DocumentNumber, Body, Full Date) Pinpoint. ReleaseType and DocumentNumber are SPACE-joined inside the brackets (eg 'Media Release MSPA 172/09'), not comma-joined like the Body/Date that follow — do not add or remove a comma there. The releasing Body is correctly omitted whenever it's the same as the Author (a very common case) — its absence is not an error.
Australian Bureau of Statistics Materials (subtype 'abs', r 7.1.5): Australian Bureau of Statistics, [Italic Title] (Catalogue No N, Full Date) Pinpoint. The author is always the fixed literal 'Australian Bureau of Statistics' — never a different or abbreviated form.
Film, Television and Other Media (subtype 'filmOrMedia', r 7.14): ['Episode Title', ][Italic Film/Series Title] (Version Details, Studio/Production Company/Producer, Date) Pinpoint <URL>. A film citation correctly has no episode title at all (r 7.14.2); a TV episode with no title of its own is correctly quoted as the literal text 'Episode N' or 'Season N, Episode N' (r 7.14.3) — treat that literal text as a normal quoted episode title, not as a placeholder to fill in. Version details are correctly present only for a non-standard version (eg 'Director's Cut') and correctly absent for the standard/theatrical version. A radio segment or podcast (r 7.14.4) correctly uses a full date rather than a bare year — do not flag a full date here as wrong just because a film/TV example nearby uses a bare year. The pinpoint is a bare time-in-recording with no comma before it (eg '0:54:58–0:55:11'), matching a report/whole-book pinpoint, not a case's comma-prefixed pinpoint. The URL is optional (r 7.14.1 says 'may be included') — its absence is not an error.
Social Media Post (subtype 'socialMedia', r 7.16): Username[ (Real Name)][, 'Title'] (Platform, Full Date[, Time][ TimeZone]) Pinpoint <URL>. The title is correctly omitted entirely (not left as an empty quoted string) when the post has none. A time is only included to disambiguate multiple same-day posts, and a time zone only when the platform adjusts the displayed time to the viewer's local zone — neither being present is correct for an ordinary single post from a zone-neutral platform. The pinpoint is a bare point-in-time/time-span with no comma before it, same as Film/TV.`,
}

// Bibliography formatting diverges from footnote/subsequent formatting in ways not covered by
// the per-source-type rule text above, and without this the validator tends to "correct" an
// already-correct bibliography back toward footnote-style formatting (eg re-adding a trailing
// full stop, or truncating a long author list to 'et al').
const BIBLIOGRAPHY_RULE = `Bibliography entry formatting (applies across all source types, and overrides anything above where they conflict): every author is listed in full — 'et al' is never used in a bibliography, no matter how many authors there are. Only the first-listed author's name is inverted to 'Surname, Given Name(s)'; every other author stays in normal 'Given Name(s) Surname' order, eg 'Ramsay, Ian and Cameron Sim'. A bibliography entry ends with no trailing full stop — it ends immediately after the citation's own final character (a page number, a closing '>', or a closing parenthesis), never with an added '.'.`

// Without this, the model has nothing to go on for what a subsequent reference should look
// like beyond copying the bibliography rule immediately above — which is the opposite of
// correct, since a subsequent reference always keeps its full stop.
const SUBSEQUENT_RULE = `Subsequent reference formatting (applies across all source types): like a footnote, a subsequent reference always ends with a trailing full stop — never omit it the way a bibliography entry does. Every source type — including the domestic 'legislation' source type (an ordinary Australian Act) — uses AGLC4 r 1.4.1's ordinary '[Short Title] (n X)[ Pinpoint].' back-reference pattern; a corrected, previous version of this rule wrongly told you legislation was an exception with no '(n X)' at all, but AGLC4's own worked example (r 1.4.1, 'ADJR Act (n 46) s 7.', explicitly annotated '[Not: ADJR Act s 7.]' for the version without the cross-reference) confirms the opposite — legislation genuinely needs '(n X)' like everything else. For domestic legislation specifically, the short title used in the subsequent reference replaces the WHOLE 'Title Year (Jurisdiction)' portion — both the year AND the jurisdiction bracket are dropped, not just the year — confirmed by that same example never showing '(Cth)' after 'ADJR Act'; do not flag a domestic legislation subsequent reference as wrong just because it lacks a jurisdiction bracket the footnote itself has.
For secondary sources specifically (journal, book, report, researchPaper, website, newspaper): AGLC4 r 1.4.1's own DEFAULT is a BARE 'Author Surname (n X) Pinpoint' with NO title at all — confirmed by its own worked example, '50 MacMillan (n 48) 41.' — the title is added only when several works by the same author are cited (undetectable by this app, since each citation is generated independently), which the source fields represent by an explicitly-populated shortTitle; a bare surname-only subsequent reference with no title is therefore CORRECT, not incomplete, whenever the source's own shortTitle field is empty — do not 'correct' it by adding the title back in. Where there are multiple authors, ALL of their surnames are joined the same and/'et al' way the footnote's own author list is (r 4.1.2), eg 'Edelman and Bant (n 2) 260.', not just the first author's. Where there is no author at all (an unsigned article, an unbylined newspaper report, a web page with no named author), the title stands in for the author's surname entirely, per r 1.4.1's own note. The one deliberate exception is the 'report' source type (r 7.1): report authors are overwhelmingly bodies/organisations in practice (Royal Commissions, government departments, regulators), which have no 'surname' to extract at all — r 1.4.1 itself says a short title is 'more helpful' than the author's name for body-authored sources, and its own worked example for exactly this case (the ALRC's 'Traditional Rights and Freedoms', r 1.4.1 example 55) drops the author entirely, using the title ALONE — so a report's own subsequent reference is correctly title-only regardless of whether an author is present, never author-plus-title or a truncated/guessed 'surname' derived from an organisation's name (eg never 'Group (n 1).' from 'Woolworths Group').`

let cachedClient: Anthropic | null = null

function getClient(): Anthropic {
  if (!cachedClient) {
    cachedClient = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
  }
  return cachedClient
}

export async function validateCitation(
  citation: CitationTexts,
  sourceType: SourceType,
  fields: CitationFields,
): Promise<ValidationResult> {
  if (!process.env.ANTHROPIC_API_KEY) {
    throw new Error('ANTHROPIC_API_KEY is not configured')
  }

  const response = await getClient().messages.parse({
    model: MODEL,
    max_tokens: 1024,
    // Byte-identical for every call against the same sourceType (this function runs on every
    // debounced keystroke in the generator, so that's extremely frequent) — cached for the same
    // latency/cost reason as ai-extract.ts's SYSTEM_PROMPT, see its own comment and CLAUDE.md.
    system: [
      {
        type: 'text',
        text: `${RULES_BY_SOURCE_TYPE[sourceType]}\n\n${BIBLIOGRAPHY_RULE}\n\n${SUBSEQUENT_RULE}`,
        cache_control: { type: 'ephemeral' },
      },
    ],
    output_config: {
      effort: 'low',
      format: zodOutputFormat(ValidationSchema),
    },
    messages: [
      {
        role: 'user',
        content: `Validate these three AGLC4 citation forms for a ${sourceType} — they are the footnote, subsequent reference, and bibliography entry for the same source, and must be corrected consistently with each other. Return JSON only: { isCorrect: boolean, correctedFootnote: string | null, correctedSubsequent: string | null, correctedBibliography: string | null, issues: string[], rule: string, confidence: 'high' | 'medium' | 'low' }. Only set a corrected* field when that specific form has an error — leave it null if that form is already correct, even if the other forms need fixing.

Footnote citation: ${citation.footnote}
Subsequent reference: ${citation.subsequent}
Bibliography entry: ${citation.bibliography}

Source fields used to generate them: ${JSON.stringify(sanitizeFieldsForValidation(fields))}`,
      },
    ],
  })

  if (response.stop_reason === 'refusal' || !response.parsed_output) {
    throw new Error(`Citation validation did not return usable output (stop_reason: ${response.stop_reason})`)
  }

  const parsed = response.parsed_output
  return {
    isCorrect: parsed.isCorrect,
    correctedFootnote: parsed.correctedFootnote ?? undefined,
    correctedSubsequent: parsed.correctedSubsequent ?? undefined,
    correctedBibliography: parsed.correctedBibliography ?? undefined,
    issues: parsed.issues,
    rule: parsed.rule,
    confidence: parsed.confidence,
  }
}
